### PR TITLE
Add "Battle Restart"

### PR DESCRIPTION
**Pull request by TheRazgriz**
Script and CDB for the anime card "Battle Restart"

### CODE REVIEW

**Comment by larry126** [comment]
I don't quite understand why the condition function has a face-up check whereas the card effect doesn't indicate so, can you explain?
```lua
function s.condition(e,tp,eg,ep,ev,re,r,rp)
	local a=Duel.GetAttacker()
	local at=Duel.GetAttackTarget()
	return at and (a:IsControler(tp) or (at:IsControler(tp) and at:IsFaceup()))
end```
"When an attack is declared involving a monster you control and an opponent's monster: "

**Comment by TheRazgriz** [comment]
I copied that condition from "Battle Fusion" and thought it was needed. If it's not, I can remove it and resubmit.

**Comment by larry126** [comment]
Battle Fusion needs it because the monster you control must be a Fusion Monster, and you need it to be face-up in order to know it is Fusion. For Battle Restart, this isn't the same case.

**Comment by TheRazgriz** [comment]
Okay, I can edit the code.

**Comment by TheRazgriz** [comment]
Edited,

**Pull request merged**
