### PR TITLE
Anime Dark Synchros

### PR DESCRIPTION
**Pull request by TheOnePharaoh**
Added Frozen Fitzgerald (Anime)
Corrected anime Dark Synchros for negative levels

### CODE REVIEW

**Comment by larry126** [comment]
Request: Remove the negative level parts
Reason: We don't have solid evidence about the level working as negative values outside of Dark Synchro Summon. And in Tag Force, they are being treated as positive levels for effect interactions (like Gravity Bind and for Xyz Summon).
I'll merge the PR once this is updated.
If you can find any evidence of them working as negative levels in effect interactions, feel free to leave a note here.

**Comment by larry126** [comment]
Request: Remove the negative level parts
Reason: We don't have solid evidence about the level working as negative values outside of Dark Synchro Summon. And in Tag Force, they are being treated as positive levels for effect interactions (like Gravity Bind and for Xyz Summon).
I'll merge the PR once this is updated.
If you can find any evidence of them working as negative levels in effect interactions, feel free to leave a note here.

**Comment by TheOnePharaoh** [comment]
@larry126 https://yugipedia.com/wiki/Dark_Wave_(anime)

**Comment by TheOnePharaoh** [comment]
this is the only negative level support card yet it proves that it works that way

**Comment by TheOnePharaoh** [comment]
@larry126 https://yugipedia.com/wiki/Dark_Wave_(anime)
this is the only negative level support card yet it proves that it works that way since it multiplied the level of a regular monster with -1 making it Negative Level

**Comment by TheOnePharaoh** [comment]
I will script Anime Dark wave later

**Comment by ClementLouis** [comment]
> https://yugipedia.com/wiki/Dark_Wave_(anime)
> this is the only negative level support card yet it proves that it works that way since it multiplied the level of a regular monster with -1 making it Negative Level

Dark wave in the anime was used on a main deck monster, not on a dark synchro, so it don't prove a dark synchro on the field is considered as having an "negative level"

also, dark wave in the anime situation basically worked in a similar way as its Tag Force counterpart (Select 1 face-up non-Tuner monster that you control. If that monster is used this turn as a Synchro Material Monster for the Synchro Summon of a Dark Synchro monster, treat its Level as a negative number.) and in Tag Force (which is our best reference for Dark Synchro stuff), the level of dark synchro after being summoned is considered as being positive for everything (being used for Xyz summon, cards effect, etc)

**Comment by TheOnePharaoh** [comment]
> > https://yugipedia.com/wiki/Dark_Wave_(anime)
> > this is the only negative level support card yet it proves that it works that way since it multiplied the level of a regular monster with -1 making it Negative Level
> 
> Dark wave in the anime was used on a main deck monster, not on a dark synchro, so it don't prove a dark synchro on the field is considered as having an "negative level"
> 
> also, dark wave in the anime situation basically worked in a similar way as its Tag Force counterpart (Select 1 face-up non-Tuner monster that you control. If that monster is used this turn as a Synchro Material Monster for the Synchro Summon of a Dark Synchro monster, treat its Level as a negative number.) and in Tag Force (which is our best reference for Dark Synchro stuff), the level of dark synchro after being summoned is considered as being positive for everything (being used for Xyz summon, cards effect, etc)
they actually had the level of the monster decrease to Negative 5 and the card proxy was clear
also Tag force changed the negative levels to positive as they would never apply Game rule breaking mechanics
for Example Xyz Monsters with Levels or negative levels
not to mention the card proxy was clear about it
https://yugipedia.com/wiki/Dark_Wave_(anime)
image

image
https://www.crunchyroll.com/yu-gi-oh-5ds/episode-48-minus-world-find-the-white-lion-regulus-666983

**Comment by larry126** [comment]
The repository is entering a lock-down state for the next few days.

**Pull request closed without merging**
