### PR TITLE
Fix for "Drop Draco"

### PR DESCRIPTION
**Pull request by Playmaker772211**

### CODE REVIEW

**Comment by kevinlul** [comment]
What exactly does this fix?

**Comment by Playmaker772211** [comment]
> What exactly does this fix?

2nd effect missing "+1" in the "SetCountLimit", now the 1st and 2nd effects can work in the same turn, sorry i forgot to write that.

**Comment by kevinlul** [comment]
Since you're modifying this, you should replace the card IDs with the `GetID` system used in other Percy scripts.

**Comment by Playmaker772211** [comment]
New one will be made with same fix and the "GetID" system.

**Pull request closed without merging**
