### PR TITLE
Updated "Performapal Longphone Bull (Anime)"

### PR DESCRIPTION
**Pull request by LogicalNonsense2051**
Judging from its current proxy and text on Yugipedia, it should also trigger if special or flip summoned as well.

### CODE REVIEW

**Comment by LuckiPhos** [comment]
Uhh could you please send a picture of the proxy & card text because it isnt exactly there on the Yugipedia page...

**Comment by LogicalNonsense2051** [comment]
Okay, never mind then. It is true that on Yugipedia, there is no exact card text for the card, only a reconstruction. And I didn't bothered to check in-game on how it was worded, just assumed it had the same text as on Yugipedia. Will have to discuss on what to do with the conflicting card texts.

**Comment by LuckiPhos** [comment]
Yeah I think the currently used version on pro is based on the IRL card, which I don't necessarily have any problems with unless there was some conflicting statement from the anime.

**Comment by LogicalNonsense2051** [comment]
Alright, talked over it and the conclusion is that we'll keep our interpretation (basing off of the real-life OCG text), rather than adapting Yugipedia's interpretation. No changes will be made to the script. Also, please don't edit the page without the approval from the Yugipedia staff, respect their interpretation of the card text.

**Pull request closed without merging**
